### ISSUE TITLE
Что нет ?

### ISSUE THREAD

**Issue by ivanLaz** [btccom/btcagent#10]
Log file created at: 2018/03/06 14:29:14
Running on machine: VIADISIAV
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0306 14:29:14.305848  7192 AgentMain.cc:106] parse json config file failure

**Comment by ivanLaz** [comment]
Где и в чём моя ошибка??? Подскажите что сделать??

**Comment by SwimmingTiger** [comment]
> parse json config file failure

It means **JSON** in the config file has bad format.

About the format of **JSON**, please visit  http://json.org/ for more information.

**Comment by ivanLaz** [comment]
И что мне там искать если я не алё в этом! Если бы был бы ас я бы не просил помощи у вас!!!

**Comment by YihaoPeng** [comment]
I want to know how do you want to use the software?
Are you a bitcoin mine owner?
Do you own hundreds or more bitcoin mining machines (bitcoin miners)?
BTCAgent is a software that help hundreds or more bitcoin miners to connect to `pool.btc.com`. It is only for the purpose.
If you don't have so many bitcoin miners, you don't need to use the software.
