### ISSUE TITLE
ola minha gente por favor mim pedoa minha falta aqui estou com muitos pobremas resolvendo mas  estou aqui ,

### ISSUE THREAD

**Issue by fty48jj19** [btccom/btcagent#16]
obrigado agradeço pela colaboraçao

**Comment by fty48jj19** [comment]
tenho 2  endereço vc pode mim achar  (  joaonativa429@gmail.com   )     ou  joaojose539@yahoo.com

**Comment by fty48jj19** [comment]
Em ter, 19 de mar de 2019 às 18:36, joao tv <notifications@github.com>
escreveu:

**Comment by fty48jj19** [comment]
ok

**Comment by fty48jj19** [comment]
ola quero deixa isso bem claro toma decisao isso cabe a mim toma essa decisao por favor aguarde aqte eu da uma decisao se quero o nao  achao que vc esta querendo cria serto pobremas  as coisa nao so asim do jeito que vc pensa e daique vc e um agente vc e um agente eu eu so o empresariarial  por favor se contanha no seu lugar nao tome medidas se eu  eu nao estou tidando essa ordem neuma decisoes ordem sao minha cabe a mim toma essas decisoes  espero que vc steja entedido no asunto   respeite as normas vc esta querendo coloca obestaculos onde nao eziste  se contenha meu amigo ,

**Comment by YihaoPeng** [comment]
The content is incomprehensible. Even with machine translation, I can't get meaningful information. It is considered as spam.
