### ISSUE TITLE
btcagent log info: setup failure

### ISSUE THREAD

**Issue by yurisyb** [btccom/btcagent#20]
Log file created at: 2019/04/29 14:20:52

Running on machine: testpool

Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0429 14:20:52.279269  6579 Server.cc:1205] add pool: pool.hashpanel.com:1800, subaccount name: testpool
I0429 14:20:52.279453  6579 Server.cc:1205] add pool: pool.hashpanel.com:443, subaccount name: testpool
I0429 14:20:52.279461  6579 Server.cc:1205] add pool: pool.hashpanel.com:3333, subaccount name: testpool
I0429 14:20:52.279752  6579 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0429 14:20:52.279826  6579 Server.cc:1223] success connect[0]: pool.hashpanel.com:1800, subaccount name: testpool
I0429 14:20:52.279884  6579 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0429 14:20:52.279920  6579 Server.cc:1223] success connect[1]: pool.hashpanel.com:1800, subaccount name: testpool
I0429 14:20:52.279971  6579 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0429 14:20:52.280005  6579 Server.cc:1223] success connect[2]: pool.hashpanel.com:1800, subaccount name: testpool
I0429 14:20:52.280055  6579 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0429 14:20:52.280087  6579 Server.cc:1223] success connect[3]: pool.hashpanel.com:1800, subaccount name: testpool
I0429 14:20:52.280135  6579 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0429 14:20:52.280169  6579 Server.cc:1223] success connect[4]: pool.hashpanel.com:1800, subaccount name: testpool
I0429 14:20:52.280186  6579 Server.cc:1579] got an error from the pool server: Connection refused
I0429 14:20:52.280238  6579 Server.cc:1579] got an error from the pool server: Connection refused
I0429 14:20:52.280287  6579 Server.cc:1579] got an error from the pool server: Connection refused
I0429 14:20:52.280336  6579 Server.cc:1579] got an error from the pool server: Connection refused
I0429 14:20:52.280385  6579 Server.cc:1579] got an error from the pool server: Connection refused
I0429 14:20:53.281494  6579 Server.cc:1194] stop tcp server event loop
E0429 14:20:53.281527  6579 AgentMain.cc:121] setup failure

Please to fix the btcagent issues

**Comment by YihaoPeng** [comment]
Is `pool.hashpanel.com:3333` your pool?
If this is yours, you should fix the stratum server first. Your server does not seem to be accessible.
```
telnet pool.hashpanel.com 3333
Trying 192.228.130.12...
telnet: Unable to connect to remote host: Resource temporarily unavailable
```

If it is not your server, you should contact the administrator of hashpanel.com to fix the the server.

Essentially, BTCAgent is a Stratum Proxy, which needs to be able to connect to pool.hashpanel.com:1800/443/3333 first, and then it can listen to 0.0.0.0:3333. If pool.hashpanel.com:1800/443/3333 is inaccessible, BTCAgent will definitely not start.

**Comment by YihaoPeng** [comment]
For your configure:
```
["pool.hashpanel.com", 1800, "testpool"],
["pool.hashpanel.com", 443, "testpool"],
["pool.hashpanel.com", 3333, "testpool"]
```
This should be three existing, accessible servers.
BTCAgent will connect to them.

After the connection is successful, the BTCAgent will listen to the following address:
```
"agent_listen_ip": "0.0.0.0",
"agent_listen_port": 3333
```

**Comment by YihaoPeng** [comment]
If you want to create a Stratum Server for pool.hashpanel.com:3333 via the BTCPool project, you should run `sserver` in the BTCPool project instead of BTCAgent. BTCAgent cannot run without an upstream Stratum Server.

**Comment by yurisyb** [comment]
I have fixed the telnet and port problem 
I can telnet now from anywhere but the issue remain,

error log:
get extra nonce1 and extra nonce2 failure


Running on machine: testpool
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0501 21:34:03.217850 16059 Server.cc:1205] add pool: pool.hashpanel.com:3333, subaccount name: rpcuser
I0501 21:34:03.218042 16059 Server.cc:1205] add pool: pool.hashpanel.com:1800, subaccount name: rpcuser
I0501 21:34:03.218050 16059 Server.cc:1205] add pool: pool.hashpanel.com:443, subaccount name: rpcuser
I0501 21:34:03.218297 16059 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0501 21:34:03.218403 16059 Server.cc:1223] success connect[0]: pool.hashpanel.com:3333, subaccount name: rpcuser
I0501 21:34:03.218449 16059 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0501 21:34:03.218511 16059 Server.cc:1223] success connect[1]: pool.hashpanel.com:3333, subaccount name: rpcuser
I0501 21:34:03.218551 16059 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0501 21:34:03.218600 16059 Server.cc:1223] success connect[2]: pool.hashpanel.com:3333, subaccount name: rpcuser
I0501 21:34:03.218638 16059 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0501 21:34:03.218683 16059 Server.cc:1223] success connect[3]: pool.hashpanel.com:3333, subaccount name: rpcuser
I0501 21:34:03.218720 16059 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0501 21:34:03.218765 16059 Server.cc:1223] success connect[4]: pool.hashpanel.com:3333, subaccount name: rpcuser
F0501 21:34:03.219017 16059 Server.cc:851] get extra nonce1 and extra nonce2 failure

**Comment by YihaoPeng** [comment]
send
> {"id": 1, "method": "mining.subscribe", "params": []}
recv
> {"id":1,"jsonrpc":"2.0","result":true}

pool.hashpanel.com:3333 is not a bitcoin/litecoin stratum server.
only bitcoin/litecoin stratum server be supported for btcagent.
if you run a `sserver`, the `type` in sserver.cfg should be one of `BTC/BCH/BSV/UBTC/SBTC/LTC`.

**Comment by YihaoPeng** [comment]
If you run btcpool, use these config files and change the `type`/`chain_type` to yours:
https://github.com/btccom/btcpool/tree/master/src/bitcoin/cfg

**Comment by yurisyb** [comment]
telnet pool.hashpanel.com 3333
send
result is:

{"id":null,"result":null,"error":[27,"Illegal params",null]}

**Comment by yurisyb** [comment]
Running on machine: testpool
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0502 15:53:55.385519 10761 Server.cc:1205] add pool: pool.hashpanel.com:3333, subaccount name: testpool
I0502 15:53:55.385681 10761 Server.cc:1205] add pool: pool.hashpanel.com:1800, subaccount name: testpool
I0502 15:53:55.385689 10761 Server.cc:1205] add pool: pool.hashpanel.com:443, subaccount name: testpool
I0502 15:53:55.385972 10761 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0502 15:53:55.386073 10761 Server.cc:1223] success connect[0]: pool.hashpanel.com:3333, subaccount name: testpool
I0502 15:53:55.386132 10761 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0502 15:53:55.386209 10761 Server.cc:1223] success connect[1]: pool.hashpanel.com:3333, subaccount name: testpool
I0502 15:53:55.386260 10761 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0502 15:53:55.386308 10761 Server.cc:1223] success connect[2]: pool.hashpanel.com:3333, subaccount name: testpool
I0502 15:53:55.386358 10761 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0502 15:53:55.386404 10761 Server.cc:1223] success connect[3]: pool.hashpanel.com:3333, subaccount name: testpool
I0502 15:53:55.386452 10761 Server.cc:67] resolve host: pool.hashpanel.com, ip: 10.1.2.33
I0502 15:53:55.386498 10761 Server.cc:1223] success connect[4]: pool.hashpanel.com:3333, subaccount name: testpool
F0502 15:53:55.386652 10761 Server.cc:851] get extra nonce1 and extra nonce2 failure

**Comment by yurisyb** [comment]
and when i use LTC replace to Sia

error:

Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0502 16:30:10.190559 17605 StratumServerMain.cc:132] LTC sserver version 2.3.2-290-ga086a01
I0502 16:30:10.191015 17605 StratumServerMain.cc:70] createServer type: LTC
I0502 16:30:10.191031 17605 StratumServer.cc:444] WORK_WITH_STRATUM_SWITCHER enabled, miners can only connect to the sserver via a stratum switcher.
I0502 16:30:10.191372 17605 StratumServer.cc:449] [Option] stale shares will be accepted.
I0502 16:30:10.191493 17605 Kafka.cc:368] producer librdkafka version: 1.0.0
I0502 16:30:10.191531 17605 Kafka.cc:368] producer librdkafka version: 1.0.0
I0502 16:30:10.191546 17605 Kafka.cc:368] producer librdkafka version: 1.0.0
I0502 16:30:10.191563 17605 Kafka.cc:81] consumer librdkafka version: 1.0.0
I0502 16:30:10.191597 17605 UserInfo.cc:45] UserInfo: user name will be case insensitive
I0502 16:30:10.191608 17605 UserInfo.cc:66] UserInfo: suffix _* will be stripped from user name
I0502 16:30:10.191669 17605 StratumServer.cc:135] set max job lifetime to 300s
I0502 16:30:10.191682 17605 StratumServer.cc:140] set mining notify interval to 30s
I0502 16:30:10.192960 17605 Kafka.cc:163] add brokers: 10.1.2.33:9092
I0502 16:30:10.193028 17605 Kafka.cc:170] create topic handle: LtcJob
I0502 16:30:10.196130 17620 StratumServer.cc:193] start job repository consume thread
I0502 16:30:10.196220 17605 Kafka.cc:442] add brokers: 10.1.2.33:9092
I0502 16:30:10.196298 17605 Kafka.cc:449] create topic handle: LtcShareLog
I0502 16:30:10.201426 17605 Kafka.cc:442] add brokers: 10.1.2.33:9092
I0502 16:30:10.201506 17605 Kafka.cc:449] create topic handle: LtcSolvedShare
I0502 16:30:10.204617 17605 Kafka.cc:442] add brokers: 10.1.2.33:9092
I0502 16:30:10.204692 17605 Kafka.cc:449] create topic handle: SiaCommonEvents
E0502 16:30:10.207813 17615 UserInfo.cc:411] invalid data, should key->value, type: 7
W0502 16:30:10.208048 17605 StratumServer.cc:780] Failed to run stratum server statistics exporter
F0502 16:30:10.208145 17605 StratumServerMain.cc:183] config missing: sserver.rsk_solved_share_topic


config file

# is using testnet3
testnet = false;

kafka = {
  brokers = "10.1.2.33:9092";

};

zookeeper = {
  brokers = "10.1.2.33:2181";
};

sserver = {
  # serverType
  type = "LTC";
  
  ip = "0.0.0.0";
  port = 3333;

  id = 1;
  zookeeper_lock_path = "/locks/sserver_sia";
  file_last_notify_time = "/work/btcpool/build/run_sserver/sserver_lastnotifytime.txt";

  tcp_read_timeout = 600;
  share_avg_seconds = 10;
  max_job_lifetime = 300;  // seconds
  default_difficulty = "4";
  max_difficulty = "4000000000000000";
  min_difficulty = "2";
  diff_adjust_period = 900;
  job_topic = "LtcJob";
  
  solved_share_topic = "LtcSolvedShare";
  share_topic = "LtcShareLog";
  common_events_topic = "SiaCommonEvents";
  enable_simulator = false;
  enable_submit_invalid_block = false;
  enable_dev_mode = false;

  dev_fixed_difficulty = 0.005;

};

users = {
    
  list_id_api_url = "https://pool.hashpanel.com/get_user_id_list.php";
  case_insensitive = true;

  strip_user_suffix = true;
  user_suffix_separator = "_";
};

prometheus = {
  enabled = true
  address = "0.0.0.0"
  port = 8080
  path = "/metrics"
};

**Comment by yurisyb** [comment]
I have changed the sserver to LTC,

Can you help me what should I add in userlist.php file
I have this file on my server but it's currently it's empty. 
error:
unable to request data from: http://localhost:8000/userlist.php?last_id=0, error: Couldn't connect to server

**Comment by yurisyb** [comment]
telnet pool.hashpanel.com 3333
send 
{"id":null,"result":"error:[27,"Illegal params",null]}

**Comment by YihaoPeng** [comment]
```
mkdir -p /var/www/html
cp get-user-list.php /var/www/html
apt install php-cli
php -S localhost:8000 -t /var/www/html
```

**Comment by YihaoPeng** [comment]
```
telnet pool.hashpanel.com 3333
# send this line to server:
{"id": 1, "method": "mining.subscribe", "params": []}

# sever response
{"id":1,"jsonrpc":"2.0","result":true}

# then send this line to server
{"params": ["rpcuser", "password"], "id": 2, "method": "mining.authorize"}

# no response from server
```

**Comment by yurisyb** [comment]
when i past the first code it give me this message:
{"id":1,"result":null,"error";[400, "client is not a stratum switcher",null]}

and second message :
# then send this line to server:
{"id":2,"result":null,"error";[25, "not subscribed",null]}

**Comment by yurisyb** [comment]
root@testpool:/work/btcagent/build# ./btcagent -c agent_conf.json -l log_btcagent
F0503 10:46:54.353585  2222 Server.cc:851] get extra nonce1 and extra nonce2 failure
*** Check failure stack trace: ***
    @     0x7f55248208ed  google::LogMessage::Fail()
    @     0x7f55248227f1  google::LogMessage::SendToLog()
    @     0x7f552482041d  google::LogMessage::Flush()
    @     0x7f55248231a9  google::LogMessageFatal::~LogMessageFatal()
    @     0x559068330921  UpStratumClient::handleStratumMessage()
    @     0x559068330d64  StratumServer::upReadCallback()
    @     0x7f55245d69b4  bufferevent_run_readcb_
    @     0x7f55245db292  bufferevent_readcb
    @     0x7f55245e0d68  event_process_active_single_queue
    @     0x7f55245e16cf  event_base_loop
    @     0x55906832b622  StratumServer::setup()
    @     0x5590683270a0  main
    @     0x7f55238b0b97  __libc_start_main
    @     0x55906832752a  _start
Aborted (core dumped)

log:
hh:mm:ss:uuuuu threadid file:line] msg
12607 agentMail.cdd:121 ] setup failure

fatal log:
success connect pool.hashpanel.com, ip 10.1.2.33
get extra nonce1 and extra nonce2 failure 

I have changed the sserver type to ltc

**Comment by YihaoPeng** [comment]
I want to do an interview, which cmake command do you use, why do you want to use it?
From [INSTALL-BTCPool.md](https://github.com/btccom/btcpool/blob/master/docs/INSTALL-BTCPool.md)
```
# Release build with 4 jobs:
cmake -DJOBS=4 -DCHAIN_TYPE=BTC -DCHAIN_SRC_ROOT=/work/bitcoin-0.16.0 ..
make -j4

# Release build at macOS:
cmake -DCHAIN_TYPE=BTC -DCHAIN_SRC_ROOT=/work/bitcoin-0.16.0 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..
make

# Debug build:
cmake -DCMAKE_BUILD_TYPE=Debug -DCHAIN_TYPE=BTC -DCHAIN_SRC_ROOT=/work/bitcoin-0.16.0 ..
make

# Build a special version of pool's stratum server, so you can run it with a stratum switcher:
# Important: This version of sserver CANNOT run independently, `Illegal params` will throw
# if you try to connect it directly without using StratumSwitcher.
# Don't use `-DPOOL__WORK_WITH_STRATUM_SWITCHER=ON` if you don't know what StratumSwitcher is.
cmake -DJOBS=4 -DCHAIN_TYPE=BTC -DCHAIN_SRC_ROOT=/work/bitcoin-0.16.0 -DPOOL__WORK_WITH_STRATUM_SWITCHER=ON ..
make -j4
```

I am very surprised why many people choose to use `-DPOOL__WORK_WITH_STRATUM_SWITCHER=ON`, even if it is pointed out that they should not use it.

In short, you should not use `-DPOOL__WORK_WITH_STRATUM_SWITCHER=ON`. If you already use it and don't want to delete the build directory, use `cmake -DPOOL__WORK_WITH_STRATUM_SWITCHER=OFF ..` to rebuild.
